### ISSUE TITLE
Windows Server 2012R2에서 오류가 있습니다.

### ISSUE THREAD

**Issue by abubaman** [sseeookk/Calibre-Aladin.co.kr-Metadata-Source-Plugin#15]
현재 Calibre 3.23.0을 사용중인 유저입니다.

Plug in을 압축 파일에서 설치하여, Calibre를 껐다가 켜고, ID(IDs가 ID로 바뀌었나 보더라구요)에 isbn:숫자 넣고 검색하면 검색이 안되더라구요.

그래서 설치된 Plugin을 더블클릭해보니 아래와 같은 에러를 보였습니다.
혹시 해결 가능한지 시간나시면 한 번 봐주시면 정말 감사하겠습니다.

-----------------------------------------

calibre, version 3.22.1
에러: 처리되지 않은 예외상황: <b>ImportError</b>:cannot import name ConfigWidget

calibre 3.22.1  embedded-python: True is64bit: False
Windows-8.1-6.3.9600-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '8.1', '6.3.9600')
Python 2.7.12+
Windows: ('8.1', '6.3.9600', 'SP0', u'Multiprocessor Free')
Interface language: ko
Successfully initialized third party plugins: Aladin.co.kr (0, 2, 0)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 290, in double_clicked
  File "site-packages\calibre\gui2\preferences\plugins.py", line 371, in modify_plugin
  File "site-packages\calibre\customize\__init__.py", line 155, in do_user_config
  File "calibre_plugins.aladin_co_kr.__init__", line 62, in config_widget
ImportError: cannot import name ConfigWidget

**Comment by sseeookk** [comment]
미안합니다.  
이제서야 늦게 이 글을 봤습니다.  
아마 https://www.mobileread.com/forums/showthread.php?t=236797 에서 0.2.0 버전을 다운 받아 쓰신 것 같네요.  
0.2.0 버전은 최신의 캘리버와는 맞지 않는 버전입니다.

 
Version 0.2.5을 써보기 바랍니다.  
[release](https://github.com/sseeookk/Calibre-Aladin.co.kr-Metadata-Source-Plugin/releases)에서 최신 버전을 다운 받기 바랍니다.
